apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: att2-may12-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: att2-may12-2
  name: att2-may12-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
